-- Super-admin support.
--
-- The 'super_admin' role is already permitted by the users.role CHECK
-- constraint in 001_init.sql, so no schema change is needed here.
--
-- This migration previously seeded a demo super-admin plus a second demo
-- campaign and its content. That demo/tenant data has been moved to
-- supabase/seed.dev.sql (local/dev only) so production is never seeded with
-- known-credential accounts or fake statistics.
--
-- To create the first production super-admin, follow the explicit bootstrap
-- steps in docs/audit/PRODUCTION-REMEDIATION.md.
